# 应用程序名称
spring:
  application:
    name: AI_Medical_Triage
  # 使用的环境（dev, test, prod)
  profiles:
    active: dev
  # 全局框架配置
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

# MyBatis 全局配置
mybatis-plus:
  type-aliases-package: com.dd.ai_medical_triage.entity
  type-handlers-package: com.dd.ai_medical_triage.handler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# 默认端口
server:
  port: 8085

# 日志配置
logging:
  level:
    root: error
    org.springframework.ai.chat.client: DEBUG
